### ISSUE TITLE
Errors on install..

### ISSUE THREAD

**Issue by fractalf** [espebra/filebin#12]
On Ubuntu 14.04.3 LTS

```
[~/go] mkdir src bin pkg
[~/go] export GOPATH=~/go
[~/go] export PATH="${PATH}:${GOPATH}/bin"
[~/go] env
...
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/alf/go/bin
GOPATH=/home/alf/go
...
[~/go] sudo apt-get install golang
[~/go] go get -d github.com/espebra/filebin
[~/go] cd src/github.com/espebra/filebin/
[~/go/src/github.com/espebra/filebin] make get-deps
go get github.com/dustin/go-humanize
go get github.com/gorilla/mux
go get github.com/gorilla/handlers
go get github.com/rwcarlsen/goexif/exif
go get github.com/disintegration/imaging
go get github.com/GeertJohan/go.rice
go get github.com/GeertJohan/go.rice/rice
[~/go/src/github.com/espebra/filebin] make install
rm -f templates.rice-box.go
rm -f static.rice-box.go
rice embed-go
go install -ldflags "-X \"main.buildstamp=`date -u '+%Y-%m-%d %H:%M:%S'`\" -X \"main.githash=`git rev-parse HEAD`\""
# github.com/espebra/filebin/app/backend/fs
app/backend/fs/fs.go:334: zw.RegisterCompressor undefined (type *zip.Writer has no field or method RegisterCompresso                                                                                 r)
# github.com/espebra/filebin/app/shared
app/shared/shared.go:12: unknown http.Client field 'Timeout' in struct literal
make: *** [install] Error 2
```

**Comment by espebra** [comment]
Hi,

Thank you for reporting.

Are you using Go version 1.6? I suspect that you'll need 1.6 or newer.

On Wed, 22 Jun 2016, 00:11 Alf Marius, <notifications@github.com> wrote:

> On Ubuntu 14.04.3 LTS
>
> [~/go] mkdir src bin pkg
> [~/go] export GOPATH=~/go
> [~/go] export PATH="${PATH}:${GOPATH}/bin"
> [~/go] env
> ...
> PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/alf/go/bin
> GOPATH=/home/alf/go
> ...
> [~/go] sudo apt-get install golang
> [~/go] go get -d github.com/espebra/filebin
> [~/go] cd src/github.com/espebra/filebin/
> [~/go/src/github.com/espebra/filebin <http://github.com/espebra/filebin/%5B~/go/src/github.com/espebra/filebin>] make get-deps
> go get github.com/dustin/go-humanize
> go get github.com/gorilla/mux
> go get github.com/gorilla/handlers
> go get github.com/rwcarlsen/goexif/exif
> go get github.com/disintegration/imaging
> go get github.com/GeertJohan/go.rice
> go get github.com/GeertJohan/go.rice/rice
> [~/go/src/github.com/espebra/filebin <http://github.com/GeertJohan/go.rice/rice%5B~/go/src/github.com/espebra/filebin>] make install
> rm -f templates.rice-box.go
> rm -f static.rice-box.go
> rice embed-go
> go install -ldflags "-X \"main.buildstamp=`date -u '+%Y-%m-%d %H:%M:%S'`\" -X \"main.githash=`git rev-parse HEAD`\""
> # github.com/espebra/filebin/app/backend/fs
> app/backend/fs/fs.go:334 <http://github.com/espebra/filebin/app/backend/fsapp/backend/fs/fs.go:334>: zw.RegisterCompressor undefined (type *zip.Writer has no field or method RegisterCompresso                                                                                 r)
> # github.com/espebra/filebin/app/shared
> app/shared/shared.go:12 <http://github.com/espebra/filebin/app/sharedapp/shared/shared.go:12>: unknown http.Client field 'Timeout' in struct literal
> make: *** [install] Error 2
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/espebra/filebin/issues/12>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAXVqvcxM46GBgowuMnrxwrndz6oEcZSks5qOGF4gaJpZM4I7OW1>
> .
>
-- 

*Espen Braastad*Senior Engineer | Varnish Software Group
Mobile: +47 93860737
We Make Websites Fly!
www.varnish-software.com
<http://files.varnish-software.com/signature.png>

**Comment by fractalf** [comment]
I was running 1.3.3 so I installed 1.6 from [this source](https://launchpad.net/~ubuntu-lxc/+archive/ubuntu/lxd-stable), still has some errors
```
[~/go/src/github.com/espebra/filebin] go version
go version go1.6 linux/amd64
[~/go/src/github.com/espebra/filebin] make install
rm -f templates.rice-box.go
rm -f static.rice-box.go
rice embed-go
go install -ldflags "-X \"main.buildstamp=`date -u '+%Y-%m-%d %H:%M:%S'`\" -X \"main.githash=`git rev-parse HEAD`\""
# github.com/espebra/filebin/app/backend/fs
app/backend/fs/fs.go:22: import /home/alf/go/pkg/linux_amd64/github.com/disintegration/imaging.a: object is [linux amd64 go1.2.1 X:none] expected [linux amd64 go1.6 X:none]
make: *** [install] Error 2
```

**Comment by espebra** [comment]
Hi,

This is probably left overs from before the upgrade. Whenever you do go get, the packages are built as well. You may delete the contents in the pkg directory (or at least the github.com/disintegration/imaging build result) and try again. It may also work out with ``go get -u all`` but I haven

**Comment by fractalf** [comment]
Removed all leftovers and tried again. Now working! Takker :)
