### ISSUE TITLE
Direct image pasting

### ISSUE THREAD

**Issue by PenaPP** [espebra/filebin#17]
Do you plan to add support for direct pasting of images (like github does in this "New issue form" or https://pasteboard.co/ does)?

**Use case**
Let's say I have an image in clipboard and I don't want to be required to open some image editor, save the image into a file, upload that file and then delete it.

**Comment by espebra** [comment]
This sounds useful. I don't have time to look into this myself at the moment, but I'd happily review and merge a pull request.

**Comment by espebra** [comment]
This feature would still be useful, but I'll not look into it myself. Feel free to contribute it as a pull request to https://github.com/espebra/filebin2. I'm closing this now.
