### ISSUE TITLE
UWP Filebin client, permission request

### ISSUE THREAD

**Issue by vpukhanov** [espebra/filebin#19]
Hello!  

I have been developing a simple Filebin upload client with C# and Universal Windows Platform. It started as more of a learning challenge, but I think that it could be really useful to some people, because Filebin doesn't require sign up and provides direct links to bins. So I was wondering if you would allow me to publish the application on the Windows Store for free. Here it is in action:  
  
![Animation of Filebin Upload client](https://i.imgur.com/ESXqNi1.gif)
  
My plan is to name it "Filebin Uploader" and put the following disclaimer into the app's description to satisfy the requirements of 3-BSD license:  
"This application is not affiliated with, endorsed, sponsored, or specifically approved by Filebit, Espen Braastad or other contributors of Filebit project and they are not responsible for it. For more information on Filebit see https://github.com/espebra/filebin"  
  
I doubt that it will be popular (Windows Store is only supported on Windows 10 and doesn't have that many users at all), but I can add a User-Agent header to all requests made by the app so you could block or throttle all of them if they become a problem.
  
Please tell me what your thoughts are!

**Comment by espebra** [comment]
Hi @vpukhanov,

This is pretty cool! It looks great, and I definitely think you should go ahead and publish it.

* A custom User-Agent header would be nice, preferably with a version marker in it to identify the version of the app used.
* If you want it to work with self-hosted filebin instances it needs to read the baseurl / host from somewhere, for example a configuration page or even some configuration file if that is easier. In this case, having ``filebin.net`` as the default is ok and will possibly be convenient for users.
* The 3-BSD license doesn't require a disclaimer, especially since you're only using the API. And as long as it's clear that it is not an official client for filebin.net I'm happy.

If you publish the source code somewhere I'll happily link to it from my repository.

**Comment by vpukhanov** [comment]
Thank you @espebra!  
  
I've gone ahead and implemented both User-Agent and self-hosted instance support. The app will identify itself as "UWP Filebin Uploader/<version>" and the first version is going to be 1.0.0  
  
I feel like adding self-hosted instances support is very important, so thank you for the suggestion! Here is a short demo:  
  
![instance hot-switching demo](https://i.imgur.com/bHN8Dl9.gif)
  
I will be publishing the source code here on GitHub soon and I'll drop the link in a comment on this issue.

**Comment by vpukhanov** [comment]
So my app did not pass Microsoft certification, because it collects personal information (Documents: device folders and files) and does not provide a privacy policy document.

Since I don't process user data and just pass it over to filebin.net (by default), I'd like to link them to filebin.net privacy policy. @espebra, does filebin.net have one? It has to answer some of the following questions:

- types of personal information collected (documents, selected by user in this case)
- description of how user can access, remove or request changes to their personal information (filebin.net web interface, I guess?)
- how the personal information will be used by service (will it be shared with third parties)
- will the users be notified of changes to the privacy policy and how

I've made the repository public, it's available at https://github.com/vpukhanov/uwp-filebin-uploader. The Releases tab of it already contains the .appxbundle for sideloading, even though it is not as safe or as convenient as installing from store.

**Comment by espebra** [comment]
Ok, not really surprising. I'll look into this when time allows and then update the issue.

**Comment by espebra** [comment]
I've been thinking for a while on how to do this. Considering that filebin is self-hosted it's not straight forward to have a privacy policy that will be accurate for all environments. However, it should be possible to explain how it works, how the files are stored and how they can be removed by the user. This can be a separate page. I'll get to it eventually, but pull requests are welcome.

**Comment by espebra** [comment]
I'm cleaning up old issues and I know this is super old. I'm not working on filebin2 which is currently available at https://dev.filebin.net/ and it has a privacy page that I believe will be sufficient and according to your request.
