### ISSUE TITLE
filebin.net not working

### ISSUE THREAD

**Issue by vpervenditti** [espebra/filebin#21]
Hi, i get internal error while im tryng to save a file. Why?

**Comment by espebra** [comment]
Hi. It was probably because the storage was full.

**Comment by Floessie** [comment]
@espebra I'm experiencing upload problems since at least yesterday. Is the storage full again?

**Comment by espebra** [comment]
Yes, it was full. Usage has increased quite a lot over the last year or so.

**Comment by Floessie** [comment]
@espebra Thanks. Fix confirmed.
> Usage has increased quite a lot over the last year or so.

We at RawTherapee do our best in promoting filebin.net as an exchange service for problematic raw files. :grin: 

Thank you (for the service and the fix)
Flössie
