### ISSUE TITLE
Every now and then "Filebin is currently unavailable"

### ISSUE THREAD

**Issue by mhadidg** [espebra/filebin#25]
I'm receiving this error message from time to time regardless of the size of the file or the number of simultaneous uploads (the case with #24);

Leaving the site for some time (to recover maybe?) resolves the issue for me.

**Comment by espebra** [comment]
There is a concurrency limit in there somewhere I believe. I'm now working on filebin version 2 (https://github.com/espebra/filebin2), so I'll not look into fixing this. It is more or less a rewrite under the hood and I don't think it has the same problem.
