### ISSUE TITLE
Download file with CURL

### ISSUE THREAD

**Issue by itaysk** [espebra/filebin#27]
the readme states that in order to download a file, we just GET it's path: https://github.com/espebra/filebin#download-file-1
However, that is fetching the HTML page, not the file itself. The download button in the UI has a `?t=` suffix, which is not deterministic. Is there a way to download files using a known URL? Did I misunderstand the readme?

**Comment by espebra** [comment]
The token (`t` query parameter) is intentionally non-deterministic to avoid abuse. For some time it was a real problem that malware was uploaded to filebin, and the link distributed by email (phishing typically). Each of the tokens are valid for 5 minutes, which basically is a window of opportunity where it is possible to copy-and-paste the URL to cURL for example. After these 5 minutes have passed, it is necessary to get a new token.

The downside to these tokens is that the URLs become non-deterministic and that API clients will have a harder time to find the right URL. This is not ideal, but I found this to be more acceptable than keep letting malware be distributed.

The readme could probably be clearer. If you self-host filebin you can choose to enable or disable these tokens. Without the tokens, the path to download a file is straightforward.

I'm currently working on a filebin version2 (https://github.com/espebra/filebin2) 
by the way. It does currently not have tokens implemented, and I'll try to come up with something better than the non-deterministic tokens. I'm not currently sure what that should be, so suggestions are appreciated.

**Comment by itaysk** [comment]
I understand why you would want to have a temporary token in the hosted filebin, just wanted to say that I found the documentation confusing. Thanks for making filebin
