### ISSUE TITLE
Handle network error gracefully on upload

### ISSUE THREAD

**Issue by bew** [espebra/filebin#28]
Hello,

Using the official website, I'm currently on an unstable network, and simple files that are ~20MB each almost always results in `Failed due to network error`.

I was thinking it would be a good idea to handle gracefully these errors to not have to start over every time.

This can be done by resuming the upload, or splitting the file in multiple chunks (of configurable-at-upload-time size?) and send each chunk one after the other, with retries if needed.. 

I know it'll not resolve itself overnight, but this might help the future me or someone else!

Thank you for anything you (or anyone else) can do about this!

**Comment by espebra** [comment]
This would be a nice addition indeed. The current behavior is to error out and clean up incomplete uploads, so some development to both the javascript and the endpoint on the server side would be needed.

I'd be happy to review a pull request for this in https://github.com/espebra/filebin2/, but I'll probably not implement this myself.

**Comment by bew** [comment]
Are you starting over with `filebin2` ?

**Comment by espebra** [comment]
Yes. I want to have a database to persistently store metadata and use s3 to store file content. Introducing these changes in the existing codebase without breaking backwards compatibility would have been too much work, so I started in a new repository. Much of the code is the same and the HTTP API is the same.

**Comment by espebra** [comment]
I'm closing this in favor of https://github.com/espebra/filebin2/issues/17
