### ISSUE TITLE
Support of special characters in filenames

### ISSUE THREAD

**Issue by vikbez** [espebra/filebin#8]
"é.png" is impossible to upload (infinite wait)

**Comment by espebra** [comment]
I'll look into it. Thank you for the bug report.

**Comment by espebra** [comment]
I've implemented a workaround in master which is deployed to http://dev.filebin.net/ now. It is not yet fixed on http://filebin.net/.

Did you experience this in a self hosted environment or on http://filebin.net/? If self hosted, is it based on master or the python branch?

**Comment by vikbez** [comment]
self hosted, on golang version (master branch)
patch seems ok !
:+1:

**Comment by espebra** [comment]
Ok. Then I'll skip backporting it to the Python version.
